---
- name: Test TCAM
  gather_facts: false
  hosts: nae
  connection: local
  tasks:
    - set_fact:
        nae_login: &nae_login
          host: 10.66.176.111
          username: admin
          password: C@ndidadmin1234
          validate_certs: false
          port: 443
    - name: Create object selector for DataBase Tier
      cisco.nae.nae_tcam:
        <<: *nae_login
        file: tcam
        ag_name: "Change Management2"
