- set_fact:
    aci_login: &aci_login
      hostname: "{{ inventory_hostname }}"
      username: "{{ aci_temp_username }}"
      private_key: "{{ './roles/aci/files/'+ aci_temp_username + '-user.key' }}"
      certificate_name: "{{ aci_temp_username }}"
      use_proxy: "no"
      validate_certs: "{{ validate_certs }}"
      port: "{{ port }}"
  when: "'apic' in group_names"

- name: Change Management - Delete old offline data sets
  shell: rm -rf ./roles/demos/files/datasets/ChangeMgmt*.tar.gz
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"

- name: Change Management - Collect Wrong Contract Scope Epoch
  script: roles/demos/files/cnae_data_collection.py -versionProperties roles/demos/files/version.properties -cnaeMode APIC -clusterName ChangeMgmtWrongScope -user "{{ admin_user }}" -password "{{ admin_pass }}" -targetDir roles/demos/files/datasets  -iterations 1 -apicConfigExportPolicyName "NAE_Export" -APIC "{{ inventory_hostname }}" 
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"

- name: Change Management - Fix Contract Scope
  cisco.aci.aci_contract:
    <<: *aci_login
    tenant: common
    contract: NP-PS_DB-P_PS_DB-contract
    scope: global
    state: present
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"

- name: Change Management - Add Overlapping Subnet
  cisco.aci.aci_bd_subnet:
    <<: *aci_login
    tenant: nae-non-prod
    bd: non-prod-db-bd
    gateway: 10.65.0.1
    mask: 24
    scope: [shared]
    state: present
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"

- pause:
    seconds: 30
    prompt: "Waiting 30 seconds to make sure ACI Config is propagated"
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"
    
- name: Change Management - Collect Correct Contract Scope but overlapping subnet Epoch
  script: roles/demos/files/cnae_data_collection.py -versionProperties roles/demos/files/version.properties -cnaeMode APIC -clusterName ChangeMgmtCorrectScopeOverlappingSubnet -user "{{ admin_user }}" -password "{{ admin_pass }}" -targetDir ./roles/demos/files/datasets -apicConfigExportPolicyName "NAE_Export"  -iterations 1 -APIC "{{ inventory_hostname }}" 
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"

- name: Change Management - Fix Overlapping Subnet
  cisco.aci.aci_bd_subnet:
    <<: *aci_login
    tenant: nae-non-prod
    bd: non-prod-db-bd
    gateway: 10.65.0.1
    mask: 24
    scope: [shared]
    state: absent
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"

- pause:
    seconds: 30
    prompt: "Waiting 30 seconds to make sure ACI Config is propagated"
  tags:
    - change_mgmt
    - alldemos
  when: "'nae' in group_names"

- name: Change Management - Collect Correct Contract Scope and Subnet
  script: roles/demos/files/cnae_data_collection.py -versionProperties roles/demos/files/version.properties -cnaeMode APIC -clusterName ChangeMgmtCorrect -user "{{ admin_user }}" -password "{{ admin_pass }}" -targetDir ./roles/demos/files/datasets -apicConfigExportPolicyName "NAE_Export"  -iterations 1 -APIC "{{ inventory_hostname }}" 
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"

- name: Change Management - Revert to Base config -  Break Contract Scope
  cisco.aci.aci_contract:
    <<: *aci_login
    tenant: common
    contract: NP-PS_DB-P_PS_DB-contract
    scope: context
    state: present
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"

- name: Change Management - Add NP-E-administration-contract as consumed to payroll-web-tier-epg
  cisco.aci.aci_epg_to_contract:
    <<: *aci_login
    tenant: nae-non-prod
    ap: payroll-ap
    epg: payroll-web-tier-epg
    contract: NP-E-administration-contract
    contract_type: consumer
    state: present
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"

- name: Change Management - Set non-prod-internal-vdi-bd to flood
  cisco.aci.aci_bd:
    <<: *aci_login
    tenant: nae-non-prod
    bd: non-prod-internal-vdi-bd
    vrf: non-prod-vrf
    l2_unknown_unicast: flood
    state: present
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"

- pause:
    seconds: 30
    prompt: "Waiting 30 seconds to make sure ACI Config is propagated"
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"

- name: Change Management - Collect Compliance Epoch
  script: roles/demos/files/cnae_data_collection.py -versionProperties roles/demos/files/version.properties -cnaeMode APIC -clusterName ChangeMgmtSegmentationCompliance -user "{{ admin_user }}" -password "{{ admin_pass }}" -targetDir ./roles/demos/files/datasets -apicConfigExportPolicyName "NAE_Export"  -iterations 1 -APIC "{{ inventory_hostname }}" 
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"

- name: Change Management - Remove NP-E-administration-contract as consumed to payroll-web-tier-epg
  cisco.aci.aci_epg_to_contract:
    <<: *aci_login
    tenant: nae-non-prod
    ap: payroll-ap
    epg: payroll-web-tier-epg
    contract: NP-E-administration-contract
    contract_type: consumer
    state: absent
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"

- name: Change Management - Restore BD to Proxy
  cisco.aci.aci_bd:
    <<: *aci_login
    tenant: nae-non-prod
    bd: non-prod-internal-vdi-bd
    vrf: non-prod-vrf
    state: present
    l2_unknown_unicast: proxy
  tags:
    - change_mgmt
    - alldemos
  when: "'apic' in group_names"