- set_fact:
    aci_login: &aci_login
      hostname: "{{ inventory_hostname }}"
      username: "{{ aci_temp_username }}"
      private_key: "{{ './roles/aci/files/'+ aci_temp_username + '-user.key' }}"
      certificate_name: "{{ aci_temp_username }}"
      use_proxy: "no"
      validate_certs: "{{ validate_certs }}"
      port: "{{ port }}"
  when: "'apic' in group_names"

- name: Delete NAE DcOps Uploaded Files
  cisco.nae.nae_file_management:
    host: "{{ inventory_hostname }}"
    username: "{{ admin_user }}"
    password: "{{ admin_pass }}"
    validate_certs: "{{ validate_certs }}"
    port: "{{ port }}"
    file: "{{ item }}"
    #Get the file name and remove the date i.e. a file name is somehting like this aci/files/datasets/ChangeMgmt2_2020-09-03_23_22_28.tar.gz
    name: "{{ item.split('/')[-1].split('_')[0] }}" 
    state: absent
  ignore_errors: yes
  with_fileglob:
    - "roles/demos/files/datasets/DcOps*.tar.gz"
  tags:
    - dcops
  when: "'nae' in group_names"

- name: Delete old offline data sets
  shell: rm -rf ./roles/demos/files/datasets/DcOps*.tar.gz
  tags:
    - dcops
  when: "'apic' in group_names"

- name: Collect Duplicate IP Epoch
  script: roles/demos/files/cnae_data_collection.py -versionProperties roles/demos/files/version.properties -cnaeMode APIC -clusterName DcOpsDupIP -user "{{ admin_user }}" -password "{{ admin_pass }}" -targetDir roles/demos/files/datasets  -iterations 1 -APIC "{{ inventory_hostname }}" 
  tags:
    - dcops
  when: "'apic' in group_names"

- name: Power Off VM with Duplicate IP 
  shell: govc vm.power -off nae-vdi-10 
  tags:
    - dcops
  when: "'vcenter' in group_names"
  environment:
    GOVC_URL: "{{ govc_url }}"
    GOVC_INSECURE: "true"
    GOVC_DATASTORE: "{{ data_store }}"

- pause:     
    minutes: 5
    prompt: "Waiting 5 minutes to ensure the duplicate IP Fault is cleared, feel free to jump ahead if you can manually check the Fault is gone in the APIC UI"
  tags:
    - dcops
  when: "'apic' in group_names"

- name: Collect No Duplicate IP Epoch
  script: roles/demos/files/cnae_data_collection.py -versionProperties roles/demos/files/version.properties -cnaeMode APIC -clusterName DcOpsNoDupIP -user "{{ admin_user }}" -password "{{ admin_pass }}" -targetDir roles/demos/files/datasets  -iterations 1 -APIC "{{ inventory_hostname }}" 
  tags:
    - dcops
  when: "'apic' in group_names"

- name: Break VDI DMZ Contract
  cisco.aci.aci_contract_subject_to_filter:
    <<: *aci_login
    tenant: nae-dmz
    contract: D-E-VDI-contract
    subject: D-E-VDI-subject
    filter: RDP
    state: absent
  tags:
    - dcops
  when: "'apic' in group_names"

- name: Collect DMZ Congtract missing filter
  script: roles/demos/files/cnae_data_collection.py -versionProperties roles/demos/files/version.properties -cnaeMode APIC -clusterName DcOpsNoFilter -user "{{ admin_user }}" -password "{{ admin_pass }}" -targetDir roles/demos/files/datasets  -iterations 1 -APIC "{{ inventory_hostname }}" 
  tags:
    - dcops
  when: "'apic' in group_names"

- name: Revert VDI DMZ Contract 
  cisco.aci.aci_contract_subject_to_filter:
    <<: *aci_login
    tenant: nae-dmz
    contract: D-E-VDI-contract
    subject: D-E-VDI-subject
    filter: RDP
    state: present
  tags:
    - dcops
  when: "'apic' in group_names"

- name: Power On VM with Duplicate IP 
  shell: govc vm.power -on nae-vdi-10 
  tags:
    - dcops
  when: "'vcenter' in group_names"
  environment:
    GOVC_URL: "{{ govc_url }}"
    GOVC_INSECURE: "true"
    GOVC_DATASTORE: "{{ data_store }}"