---
- name: Power Off VM
  shell: govc vm.power -off nae-vdi-{{ item }}
  with_sequence: start=1 end=10
  ignore_errors: yes
  async: 10
  poll: 0
  register: _create_instances
  tags:
    - cleanup
    - delete_vms
- name: Wait for VMs to be off
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: result
  until: result.finished
  retries: 30
  with_items: "{{ _create_instances.results }}"
  ignore_errors: yes
  tags:
    - cleanup
    - delete_vms


- name: Delete VMs
  shell: govc vm.destroy nae-vdi-{{ item }}
  with_sequence: start=1 end=10
  ignore_errors: yes
  async: 10
  poll: 0
  tags:
    - cleanup
    - delete_vms

- name: Power Off DMZ VM
  shell: govc vm.power -off nae-dmz-vdi-{{ item }}
  with_sequence: start=1 end=9
  ignore_errors: yes
  async: 10
  poll: 0
  register: _create_instances
  tags:
    - cleanup
    - delete_vms

- name: Wait for DMZ VMs to be off
  async_status:
    jid: "{{ item.ansible_job_id }}"
  register: result
  until: result.finished
  retries: 30
  with_items: "{{ _create_instances.results }}"
  ignore_errors: yes
  tags:
    - cleanup
    - delete_vms

- name: Delete DMZ VMs
  shell: govc vm.destroy nae-dmz-vdi-{{ item }}
  with_sequence: start=1 end=9
  ignore_errors: yes
  async: 10
  poll: 0
  tags:
    - cleanup
    - delete_vms