---
- name: install govc locally
  shell: "curl -L https://github.com/vmware/govmomi/releases/download/v0.23.0/govc_linux_amd64.gz | gunzip > roles/vms/files/govc "
  tags:
    - install_govc

- name: ensure govc is executable
  shell: chmod +x roles/vms/files/govc
  tags:
    - install_govc

- name: Clone VM
  shell: govc vm.clone -vm "{{ linked_clone_vm }}" -snapshot  $(govc snapshot.tree -vm  "{{ linked_clone_vm }}"  -C ) -on=false -link=true nae-vdi-{{ item }}
  tags:
    - vms
  with_sequence: start=1 end=10

- name: Configure VM Port Group
  shell: govc vm.network.change -vm nae-vdi-{{ item }} -net "{{ dvs_path }}nae-non-prod|internal-vdi-ap|internal-vdi-desktops-epg" ethernet-0
  tags:
    - vms
  with_sequence: start=1 end=10

- name: Configure VM IPs
  shell: govc vm.customize -vm nae-vdi-{{ item }} -name VM-{{ item }} -gateway 10.18.0.1 -ip 10.18.0.2{{ item }} -netmask 255.255.255.0 -dns-server 8.8.8.8
  tags:
    - vms
  with_sequence: start=1 end=9

- name: Configure VM with Duplicate IP
  shell: govc vm.customize -vm nae-vdi-10 -name VM-10 -gateway 10.18.0.1 -ip 10.18.0.26 -netmask 255.255.255.0 -dns-server 8.8.8.8
  tags:
    - vms

- name: PowerOn VM
  shell: govc vm.power -on nae-vdi-{{ item }}
  tags:
    - vms
  with_sequence: start=1 end=10

- name: Wait for all VMs IP
  shell: govc vm.ip nae-vdi-{{ item }}
  tags:
    - vms
  with_sequence: start=1 end=10